Simple TLU Perceptron on iris dataset

In [74]:
from sklearn.datasets import load_iris
import numpy as np
from sklearn.linear_model import Perceptron

In [75]:
dataset = load_iris()

In [76]:
dataset.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [77]:
x = dataset.data
y= dataset.target

In [78]:
x[:6]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4]])

In [79]:
y[:6]

array([0, 0, 0, 0, 0, 0])

In [80]:
x[:10]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [81]:
x = x[:,(2,3)]
y = (y == 0).astype(int)

In [82]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.9)

In [83]:
prd_clf= Perceptron()

In [84]:
from sklearn.model_selection import cross_val_score
score = cross_val_score(prd_clf,x_train,y_train,cv=5,n_jobs=-1)

In [85]:
score.mean()

np.float64(1.0)