In [46]:
import tensorflow as tf
from tensorflow import keras
import numpy as np

In [47]:
tf.__version__

'2.22.0-dev20260731'

In [48]:
keras.__version__

'3.16.0.dev2026073104'

In [49]:
fashion_mnist = keras.datasets.fashion_mnist

In [50]:
(x_train,y_train),(x_test,y_test) = fashion_mnist.load_data()

In [51]:
x_valid, x_train = x_train[:5000]/255.0 , x_train[5000:]/255.0
y_valid , y_train = y_train[:5000], y_train[5000:]

In [52]:
y_train[:10]

array([4, 0, 7, 9, 9, 9, 4, 4, 3, 4], dtype=uint8)

In [53]:
np.unique(y_train)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=uint8)

In [54]:
model = keras.models.Sequential()
model.add(keras.layers.Flatten(input_shape =[28,28]))
model.add(keras.layers.Dense(300,activation="relu"))
model.add(keras.layers.Dense(100,activation="relu"))
model.add(keras.layers.Dense(10,activation="softmax"))

/home/yogesh/.local/lib/python3.14/site-packages/keras/src/layers/reshaping/flatten.py:37: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [55]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ flatten_3 (Flatten)             │ (None, 784)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 300)            │       235,500 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 100)            │        30,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_8 (Dense)                 │ (None, 10)             │         1,010 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 266,610 (1.02 MB)

 Trainable params: 266,610 (1.02 MB)

 Non-trainable params: 0 (0.00 B)

In [56]:
model.layers

[<Flatten name=flatten_3, built=True>,
 <Dense name=dense_6, built=True>,
 <Dense name=dense_7, built=True>,
 <Dense name=dense_8, built=True>]

In [57]:
layer1 = model.layers[1]
layer1.name

'dense_6'

In [58]:
weights, bias = layer1.get_weights()

In [59]:
weights

array([[-0.07009044, -0.06560627,  0.01635057, ..., -0.03627774,
         0.06982321,  0.02028391],
       [ 0.06249692, -0.04254426,  0.02335706, ..., -0.04914095,
         0.00070447,  0.0125713 ],
       [ 0.07236512,  0.03536705, -0.03888907, ...,  0.072598  ,
        -0.04130939, -0.00336655],
       ...,
       [-0.02883948,  0.01860181, -0.03097205, ...,  0.04255478,
         0.05064237, -0.03241447],
       [ 0.04282578, -0.05467846, -0.020772  , ..., -0.02594883,
         0.05088033,  0.04979908],
       [ 0.05753754, -0.05286004,  0.03822734, ...,  0.07063799,
        -0.02786771,  0.0068936 ]], shape=(784, 300), dtype=float32)

In [60]:
bias

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0.

In [61]:
model.compile(loss="sparse_categorical_crossentropy",
optimizer="sgd",
metrics=["accuracy"])

In [62]:
# history = model.fit(x_train,y_train,epochs=30,validation_batch_size=(x_valid,y_valid))

Epoch 1/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.7663 - loss: 0.7109
Epoch 2/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8309 - loss: 0.4885
Epoch 3/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8449 - loss: 0.4435
Epoch 4/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8540 - loss: 0.4156
Epoch 5/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8606 - loss: 0.3949
Epoch 6/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8662 - loss: 0.3782
Epoch 7/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8713 - loss: 0.3643
Epoch 8/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8747 - loss: 0.3523
Epoch 9/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8778 - loss: 0.3419
Epoch 10/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8817 - loss: 0.3325
Epoch 11/30
1719/1719 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - accuracy: 0.8843 - loss: 0.3239
Epoch 12/30
 535/1719 ━━━━━━━━

KeyboardInterrupt: 

In [ ]:
# model.evaluate(x_train,y_train)

1719/1719 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - accuracy: 0.9167 - loss: 0.2300


[0.23000682890415192, 0.9167454838752747]

In [63]:
from sklearn.datasets import fetch_california_housing
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [64]:
data = fetch_california_housing()

In [65]:
x = data.data
y = data.target

In [66]:
x = StandardScaler().fit_transform(x)

In [67]:
x_train_full,x_test,  y_train_full, y_test = train_test_split(x,y,test_size=0.1)

In [68]:
x_train, x_valid , y_train, y_valid = train_test_split(x_train_full,y_train_full,test_size=0.1)

In [91]:
model = keras.models.Sequential([keras.layers.Dense(30,activation="relu",input_shape= x_train[1].shape),keras.layers.Dense(1)])

In [92]:
model.compile(loss= keras.losses.mse,optimizer=keras.optimizers.SGD())

In [93]:
history = model.fit(x_train,y_train,epochs=30,validation_data=(x_valid,y_valid))

Epoch 1/30


523/523 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.7462 - val_loss: 0.4119
Epoch 2/30
523/523 ━━━━━━━━━━━━━━━━━━━━ 0s 686us/step - loss: 0.4533 - val_loss: 0.3720
Epoch 3/30
523/523 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 0.4212 - val_loss: 0.3537
Epoch 4/30
523/523 ━━━━━━━━━━━━━━━━━━━━ 0s 801us/step - loss: 0.4044 - val_loss: 0.3436
Epoch 5/30
523/523 ━━━━━━━━━━━━━━━━━━━━ 0s 721us/step - loss: 0.3954 - val_loss: 0.3374
Epoch 6/30
523/523 ━━━━━━━━━━━━━━━━━━━━ 0s 757us/step - loss: 0.3871 - val_loss: 0.3319
Epoch 7/30
523/523 ━━━━━━━━━━━━━━━━━━━━ 0s 765us/step - loss: 0.3816 - val_loss: 0.3271
Epoch 8/30
523/523 ━━━━━━━━━━━━━━━━━━━━ 0s 857us/step - loss: 0.3776 - val_loss: 0.3233
Epoch 9/30
523/523 ━━━━━━━━━━━━━━━━━━━━ 0s 856us/step - loss: 0.3738 - val_loss: 0.3187
Epoch 10/30
523/523 ━━━━━━━━━━━━━━━━━━━━ 0s 708us/step - loss: 0.3704 - val_loss: 0.3147
Epoch 11/30
523/523 ━━━━━━━━━━━━━━━━━━━━ 0s 696us/step - loss: 0.3673 - val_loss: 0.3116
Epoch 12/30
523/523 ━━━━━━━━━━━━━━━━━━━━ 0s 7

In [94]:
model.evaluate(x_test,y_test)

65/65 ━━━━━━━━━━━━━━━━━━━━ 0s 994us/step - loss: 0.3513


0.3512566089630127